export const HOME_TRANSMISSION_MATERIAL_CONFIG = {
  backside: true,
  samples: 16,
  resolution: 1024,
  clearcoat: 0,
  clearcoatRoughness: 0.0,
  thickness: 0.35,
  chromaticAberration: 5,
  anisotropy: 0.3,
  roughness: 0.0,
  distortion: 0.5,
  distortionScale: 1,
  temporalDistortion: 0.4,
  ior: 0.83,
  transmission: 0.8,
  color: '#ffc300',
  gColor: '#87ceeb',
  envMapIntensity: 1,
  reflectivity: 0.05,
  shadow: '#87ceeb',
  emissive: '#fff',
  emissiveIntensity: -0.075,
};
